# Generated by Django 5.2.8 on 2026-04-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap_id', models.CharField(default='tap_1', max_length=50)),
                ('liters_requested', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
