# Generated by Django 5.2.8 on 2026-04-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterorder',
            name='water_type',
            field=models.CharField(choices=[('normal', 'Normal Water'), ('cold', 'Cold Water'), ('hot', 'Hot Water')], default='normal', max_length=10),
        ),
    ]
